#!/usr/bin/env bash

function choice {
    CHOICE=''
    local prompt="$*"
    local answer
    read -p "$prompt" answer
    case "$answer" in
        [yY1] ) CHOICE='y';;
        [nN0] ) CHOICE='n';;
        *     ) CHOICE="$answer";;
    esac
} # end of function choice

function help {
    echo -e "\e[7m\e[31mYou need choose a Servername.\e[0m\e[0m"
    echo "If you not choose a document root, your will be /var/www/SERVERNAME."
    echo "usage: sudo dev"
}

if [ "$1" == 'help' ] || [ "$1" == '-h' ]; then
    help
else
	choice "Choice your servername: "
		if [ -n "$CHOICE" ]; then
			 SERVERNAME="$CHOICE"
		else
    	 SERVERNAME=""
		fi

	choice "Choice your Document Root or Press Enter: "
		if [ -n "$CHOICE" ]; then
			ROOT="$CHOICE"
		else
			ROOT="$SERVERNAME"
		fi

	if [ "$SERVERNAME" == '' ]; then
		help
	else
		if [ ! -d "/var/www/$ROOT" ]; then
    		mkdir "/var/www/$ROOT"
  	fi
  	
    cd "/var/www/$ROOT"
  		
		VHOSTDIR="/etc/apache2/sites-available/"
		EXTENSION=".conf"
		RESTARTCMD="/usr/bin/sudo service apache2 reload"

VHOST=$(cat <<EOF
<VirtualHost *:80>
    ServerName $SERVERNAME
    DocumentRoot /var/www/$ROOT
    SetEnv APPLICATION_ENV "development"

    <Directory /var/www/$ROOT>
        DirectoryIndex index.php
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>

<IfModule mod_headers.c>
    # Serve gzip compressed CSS files if they exist 
    # and the client accepts gzip.
    RewriteCond "%{HTTP:Accept-encoding}" "gzip"
    RewriteCond "%{REQUEST_FILENAME}\.gz" -s
    RewriteRule "^(.*)\.css" "$1\.css\.gz" [QSA]

    # Serve gzip compressed JS files if they exist 
    # and the client accepts gzip.
    RewriteCond "%{HTTP:Accept-encoding}" "gzip"
    RewriteCond "%{REQUEST_FILENAME}\.gz" -s
    RewriteRule "^(.*)\.js" "$1\.js\.gz" [QSA]


    # Serve correct content types, and prevent mod_deflate double gzip.
    RewriteRule "\.css\.gz$" "-" [T=text/css,E=no-gzip:1]
    RewriteRule "\.js\.gz$" "-" [T=text/javascript,E=no-gzip:1]


    <FilesMatch "(\.js\.gz|\.css\.gz)$">
      # Serve correct encoding type.
      Header append Content-Encoding gzip

      # Force proxies to cache gzipped & 
      # non-gzipped css/js files separately.
      Header append Vary Accept-Encoding
    </FilesMatch>
</IfModule>

<IfModule mod_expires.c>
# Enable expirations
ExpiresActive On
# Default directive
ExpiresDefault "access plus 1 month"
# My favicon
ExpiresByType image/x-icon "access plus 1 year"
# Images
ExpiresByType image/gif "access plus 1 month"
ExpiresByType image/png "access plus 1 month"
ExpiresByType image/jpg "access plus 1 month"
ExpiresByType image/jpeg "access plus 1 month"
# CSS
ExpiresByType text/css "access plus 0 seconds"
# Javascript
ExpiresByType application/javascript "access plus 0 seconds"
</IfModule>
EOF
)

		if [ ! -f "$VHOSTDIR$SERVERNAME" ]; then
    		echo "${VHOST}" > $SERVERNAME$EXTENSION
    		mv "$SERVERNAME$EXTENSION" "$VHOSTDIR"
    		echo "created $VHOSTDIR$SERVERNAME$EXTENSION"
  		else
    		mv "$VHOSTDIR$SERVERNAME$EXTENSION" "$VHOSTDIR$SERVERNAME$EXTENSION.bak"
    		echo "${VHOST}" > /etc/apache2/sites-available/$SERVERNAME$EXTENSION
    		echo "created $VHOSTDIR$SERVERNAME$EXTENSION and made a backup of the existing conf"
  		fi
  		sudo a2ensite $SERVERNAME$EXTENSION
  		myHostName=$SERVERNAME
  		echo "127.0.0.1 $myHostName" >>/etc/hosts
  		echo "Reloading Apache"
  		$RESTARTCMD
  		echo "reloaded apache"
  	fi
fi
